### ISSUE TITLE
the week number in the calendar

### ISSUE THREAD

**Issue by gregnix** [aplsimple/pave#1]
Hello,
a wish in pave - calendar

(Or a hint on how I can try it myself)

the week number in the calendar

-  https://wiki.tcl-lang.org/page/widget%3A%3Acalendar
-  https://core.tcl-lang.org/tklib/doc/trunk/embedded/md/tklib/files/modules/widget/widget_calendar.md

`used %V`

-  http://www.tcl.tk/man/tcl/TclCmd/clock.htm#M67

```
%V On output, produces the number of the ISO8601 week as a two digit number (01-53). Week 01 is the week 
containing January 4; or the first week of the year containing at least 4 days; or the week containing the first 
Thursday of the year (the three statements are equivalent). Each week begins on a Monday. On input, accepts 
the ISO8601 week number in determining an input date. It is not the ISO8601 week number; that week is produced 
and accepted by %V. 
```

-  http://www.tcl.tk/man/tcl/TclCmd/clock.htm#M69

```
%W On output, produces a week number (00-53) within the year; week 01 begins on the first Monday 
of the year. On input, accepts two digits, which are otherwise ignored. This format group is never used 
in determining an input date. It is not the ISO8601 week number; that week is produced and accepted by %V. 
```

Gregor

**Comment by aplsimple** [comment]
If you want just to get dates including week number, refer to the setting:

`Preferences/Templates/Date format`

and set e.g.

`%d %b %Y - %V`

If the week numbers are wanted to be shown somewhere at left/right edge of the calendar, then it needs a bit of work. I'd prefer not overloading this thing, just showing weeks in tooltips or alike way, as the weeks are rarely wanted imho.

**Comment by gregnix** [comment]
> If the week numbers are wanted to be shown somewhere at left/right edge of the calendar, then it needs a bit of work. I'd prefer not overloading this thing, just showing weeks in tooltips or alike way, as the weeks are rarely wanted imho.

I use the week number all the time, but there is already a solution with calendar widget from the tklib. So it's not necessary to change the pave calendar.

**Comment by aplsimple** [comment]
Would you share how you use the week numbers?

I'm interested, for some reasons. For an app I have in mind to be developed soon.

**Comment by gregnix** [comment]
I use the week at work all the time. 
Whether it's the delivery week, vacations or appointments, I always look at the week first. The month is secondary. The same applies in my private life.
I guess it depends on how you plan your time.

**Comment by aplsimple** [comment]
OK, I'll include tklib calendar in Edit/Formats/Pluginable. Thanks for prompting.

**Comment by gregnix** [comment]
> OK, I'll include tklib calendar in Edit/Formats/Pluginable, it's in alited. I'll see whether it makes sense to inject alited's code into apave package, as alternative.
> 
> Thanks for prompting.

Thanks, but:
If the calendar widget is called up but no date is selected, but you want to continue directly in the alited window, the calendar widget is behind the window and blocks the entries.
( vwait $tvar)

or
wm attributes window ?option value option value...?
       -topmost
        Specifies whether this is a topmost window (displays above all other windows).

**Comment by aplsimple** [comment]
Yes, I know this problem. The calendar can be found in the task bar, but it's definitely not fine. I'll try to solve this anyway. Btw the same issue can be seen in some other Tcl/Tk apps, even made by notorious authors.😕

Also I am going to add `-weeks` option to both apave calendars (stand-alone and embedded) meaning "switch showing week numbers on/off". There will be an appropriate switch in alited's Setup menu.

**Comment by aplsimple** [comment]
Added `-weeks` option to calendars, it can be:
  0 - no weeks
  1 - standard mode
  2 - "sticky" mode
All modes are implemented in alited (set up in Setup menu).

**Comment by gregnix** [comment]
Thanks,
better than how I imagined it
