### ISSUE TITLE
Change appearance of Menubar

### ISSUE THREAD

**Issue by georgtree** [aplsimple/pave#3]
Hello!
My question is - how to change the style of menubar? I tried to do that with styles, but it remains raised above other items:
![image](https://github.com/user-attachments/assets/3ae95091-e95a-4262-8338-f53e322cbabd)
Thank you in advance, George.

**Comment by aplsimple** [comment]
Hi,
I'm afraid I didn't understand the question. How do you want the menu bar to be changed? Also, the menu bar is always on the top of the application window, i.e. above other widgets, not?
Note also: in Windows the menu bars aren't modifiable by Tk, being styled by the OS only.

**Comment by georgtree** [comment]
Hello, I mean the border shape with imitation of shadow

**Comment by aplsimple** [comment]
The apave doesn't provide this functionality and I don't even know why it's required at all, especially nowadays when the ubiquitous hamburgers are replacing the menu bars.

Nonetheless, I would try the following code:

 ```
option add *Menu.background $colors(menu.bg)
option add *Menu.foreground $colors(menu.fg)
option add *Menu.activeBackground $colors(select.bg)
option add *Menu.activeForeground $colors(select.fg)
 option add *Menu.disabledForeground $colors(fg.disabled)
option add *Menu.selectColor $colors(menu.fg)
option add *Menu.relief $colors(menu.relief)
# don't scale the borderwidth here
option add *Menu.borderWidth 1
```

It's taken from **awthemes** package, you can google it.
