### ISSUE TITLE
Text widget braces highlightning

### ISSUE THREAD

**Issue by georgtree** [aplsimple/pave#6]
Hello!
Could you please elaborate where/how I can control the braces/brackets highlighting while putting cursor on it?
The issue I faced is that when I create a new window with text widget inside, the braces highlighting works well, but after I
create new window the second time, this highlighting doesn't work, and not work until I restart the app.
Thank you in advance!

**Comment by georgtree** [comment]
I encounter the same issue with detached window - if I detached the second time, it stops highlighting matched braces

**Comment by georgtree** [comment]
Also highlighting of selected line also becomes broken

**Comment by georgtree** [comment]
Made a video
https://github.com/user-attachments/assets/8cfb6f9d-47c7-44f8-9da5-00d124a28609

**Comment by aplsimple** [comment]
Hi George,

Thanks for the scrupulous feedback.

The issue's cause is the *-dobind* option of *hl_init* set as 0 (false) by default.

The option seems overkill as *BindToEvent* proc binds the hl_tcl's stuff only once for a text widget.

So, you've noticed indeed **two issues**: one with the second highlighting and one with the unnecessary code. Both will be fixed soon.

Thanks a lot.

**Comment by aplsimple** [comment]
Fixed in hl_tcl package. So that, in apave and alited too.

**Comment by georgtree** [comment]
Great, thank you!
