### ISSUE TITLE
Gutter appears only when I hover mouse over text widget

### ISSUE THREAD

**Issue by georgtree** [aplsimple/pave#8]
Hello!
Gutter works well, the only issue is that it appears near text widget only after hovering mouse over the text widget.
How could I resolve this?
Thank you in advance!

**Comment by aplsimple** [comment]
Use the snippet from alited's code as a sample:

```
proc main::UpdateGutter {} {
  # Redraws the gutter.

  namespace upvar ::alited obPav obPav
  set wtxt [CurrentWTXT]
  after idle [list after 0 "$obPav fillGutter $wtxt"]
}
```
Here, $obPav refers to the apave object that layouts the text and its gutter, $wtxt is the text's path.

**Comment by georgtree** [comment]
Hello, I don't quite understand the command CurrentWTXT and where I should run this procedure :(

**Comment by georgtree** [comment]
I tried like that:

```tcl
  proc UpdateGutter {} {
      namespace upvar ::modelTestVerTool::gui::unifiedTestWin objPave objPave
      set wtxt .winUnTest.fra.pan.panCode.lfrCode.texCode
      after idle [list after 0 "$objPave fillGutter $wtxt"]
  }
  UpdateGutter
```
`.winUnTest.fra.pan.panCode.lfrCode.texCode` - full path to text widget, `paveUnifiedTestWin` - name of pave object
The error is:
```
invalid command name "paveUnifiedTestWin"
invalid command name "paveUnifiedTestWin"
    while executing
"paveUnifiedTestWin fillGutter .winUnTest.fra.pan.panCode.lfrCode.texCode"
    ("after" script)
```

**Comment by aplsimple** [comment]
UpdateGutter proc needs no "namespace upvar", the sample above is just a sample. You can use your own variable for the $objPave, including a global one if not a fully qualified.

As for calling it: supposedly, at problems, you call UpdateGutter *after* a fully layouted Tk window and *before* it goes in the event cycle.

At using apave package, this means *after* paveWindow and *before* showModal procedures. Also, I should note that filling/updating the gutter can be needed in some other cases and can present some problems in those cases which are very individual. No universal recepts for any case, alas.

Try and keep much of patience at dealing with Tcl/Tk, excuse me for the moralising (I've passed through this stuff some years ago, so I may do this moralising, sorry).

**Comment by georgtree** [comment]
Hello, no problems, I updated procedure to: 
```tcl
proc UpdateGutter {} {
            # Redraws the gutter.
            set wtxt .winUnTest.fra.pan.panCode.lfrCode.texCode
            after idle [list after 0 "::modelTestVerTool::gui::unifiedTestWin::paveUnifiedTestWin fillGutter $wtxt"]
        }
```
it doesn't throw a error, but issue still persist.
I tried to call this procedure in many places, before text insert and after, before showModal call, no effect :(

```tcl
proc fillCodeText {} {
            variable locVars
            .winUnTest.fra.pan.panCode.lfrCode.texCode delete 0.0 end
            UpdateGutter
            .winUnTest.fra.pan.panCode.lfrCode.texCode insert end [string trim $locVars(code)]
            UpdateGutter
            return
       }
fillCodeText
UpdateGutter
UpdateGutter
set res [$objPave showModal $win -decor 1 -escape no -resizable 1 -modal no]
```

Where could I look also?

**Comment by georgtree** [comment]
I found the issue, I should update gutter with delay:

```tcl
after idle [list after 200 "::modelTestVerTool::gui::unifiedTestWin::paveUnifiedTestWin fillGutter $wtxt"]
```

Thank you for help!

P.S. It's often happens when I solve the problem talking to myself like here...

**Comment by aplsimple** [comment]
In v4.4.10, I made it simplified.

So that you can call **fillGutter** just after the text updated:

```
.tex insert end $texcont
apave::obj fillGutter .tex
```

**Comment by georgtree** [comment]
Got it, thank you, all works!
