### ISSUE TITLE
Allow window to be resizable only in one direction (along one axis)

### ISSUE THREAD

**Issue by georgtree** [aplsimple/pave#9]
Hello!
Is it possible to allow window to be resizable only in one direction, x for example?
I found only option -resizable for both axes.
Thank you in advance!

**Comment by aplsimple** [comment]
Yes, you can use *-resizable 1* or  *-resizable 0* to switch the resizing on/off in both directions.

Alternatively, use *-resizable {1 0}* or *-resizable {0 1}* for X or Y axis only.

To set an option's default value for all windows processed by apave,  e.g. for resizing X axis only, use the command:

```
apave::obj setShowOption -resizable {1 0}
```


It's just a syntactic sugar for Tk's *wm resizable* command that can be used dynamically as well.
